### ISSUE TITLE
 No rule to make target

### ISSUE THREAD

**Issue by WhiteD1978** [noob404yt/belize-5.15.15-mt7668-dns-vpn#1]
[rhino@fedora belize-5.15.15-mt7668-dns-vpn]$ make -j7
  DESCEND objtool
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
make[4]: *** No rule to make target '/lib/firmware/mrvl/sd8897_uapsta.bin', needed by 'drivers/base/firmware_loader/builtin/mrvl/sd8897_uapsta.bin.gen.o'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [scripts/Makefile.build:540: drivers/base/firmware_loader/builtin] Error 2
make[2]: *** [scripts/Makefile.build:540: drivers/base/firmware_loader] Error 2
make[1]: *** [scripts/Makefile.build:540: drivers/base] Error 2
make: *** [Makefile:1868: drivers] Error 2
make: *** Waiting for unfinished jobs...

**Comment by noob404yt** [comment]
Sorry for the missing `bzImage` in the command. Corrected on the [article](https://ps4linux.com/ps4-baikal-belize-mt7768-vpn-opensource/#Step_3_Compile_PS4_Linux_kernel_from_downloaded_source).

**Comment by WhiteD1978** [comment]
got it. thanks
