### ISSUE TITLE
Add Docker support in the kernel.

### ISSUE THREAD

**Issue by seuros** [noob404yt/belize-5.15.15-mt7668-dns-vpn#2]
I use my PS4 as a docker host, however the kernel is missing some flags that cause no issue for other operations.

Will you accept a PR that add those flags ?

**Comment by noob404yt** [comment]
I have been meaning to add Docker options to the kernels since [Honeygain](https://ps4linux.com/make-money-pc-mobile-ps4-honeygain/) uses Docker. I will soon add those. If you want, you can specify the tags that you want enabled. I will add them via a commit.
